version: '3.5' # We use version 3.5 syntax

services: # Here we define our service(s)
  cloudabis.web.sample: # The name of the service
    image:  docker push cloudabis/web-sample:sample-2.1.0  #docker image or other image
    container_name: cloudabis-web-sample-2.1.0 # Container name
    build:  # Location of our Dockerfile
      context: .
      dockerfile: Dockerfile
    environment:
     NODE_ENV: production
    volumes: # Volume binding
      - './:/app' 
    ports: 
      - '7090:7090' # Port mapping
    restart: always